### ISSUE TITLE
页面渲染后没有 toc 内容块

### ISSUE THREAD

**Issue by ikonglong** [ahonn/hexo-theme-even#213]
蛮喜欢这个 theme，但是页面渲染后没有 toc 内容块。
==========================
package.json 内容如下：
```json
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.7.1"
  },
  "dependencies": {
    "hexo": "^3.7.1",
    "hexo-generator-archive": "^0.1.5",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-feed": "^1.2.2",
    "hexo-generator-index": "^0.2.1",
    "hexo-generator-tag": "^0.2.0",
    "hexo-inject": "^1.0.0",
    "hexo-math": "^3.0.4",
    "hexo-renderer-ejs": "^0.3.1",
    "hexo-renderer-markdown-it": "^3.4.1",
    "hexo-renderer-scss": "^1.2.0",
    "hexo-renderer-stylus": "^0.3.3",
    "hexo-server": "^0.3.1"
  }
}
```

hexo _config.yml 中相关的配置：
```
...

# Hexo Plugins Config

# Markdown-it config
## Docs: https://github.com/celsomiranda/hexo-renderer-markdown-it/wiki
markdown:
  anchors:
    level: 2
    collisionSuffix: 'v'
    permalink: true
    permalinkClass: header-anchor
    permalinkSymbol: ¶

...
```
even _config.yml 内容：
```
...
# Site creation time
since: 2015

# Custom your favicon.ico in `site/source`
favicon: /favicon.ico

# Set feed link (false | default | your feed link)
# false: disable
# default: use `atom.xml`, generator for `hexo-generator-feed`
rss: default

# ===========================================
# Menu Settings
# ===========================================
menu:
  Home: /
  Categories: /categories
  Tags: /tags
  Archives: /archives/
  About: /about

# ===========================================
# Theme Settings
# ===========================================
# color: Default | Mint Green | Cobalt Blue | Hot Pink | Dark Violet
theme:
  color: Mint Green
  #toc: true
  #fancybox: true
  #pjax: true

toc: true

fancybox: true

pjax: true

copyright:
  enable: true
  # https://creativecommons.org/
  license: '<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/" target="_blank">知识共享署名-非商业性使用 4.0 国际许可协议</a>'
...
```
