### ISSUE TITLE
好像不支持latex数学公式？

### ISSUE THREAD

**Issue by gnodidux** [ahonn/hexo-theme-even#218]
好像不能写公式，可否添加下支持，谢谢。

**Comment by onns** [comment]
首先通过npm安装`hexo-math`, 不知道为什么要连续执行两次才能执行成功.

``` bash
npm install hexo-math --save
npm install hexo-math --save
```

修改网站根目录的`_config.yml`, 添加如下内容: 

```
math:
  engine: 'mathjax' # or 'katex'
  mathjax:
    src: "//cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"
    config:
      # MathJax config
```
用法在: [hexo-math](https://github.com/hexojs/hexo-math)
推荐使用`{% math %}...{% endmath %}`这样的写法.

**Comment by onns** [comment]
> 好像不能写公式，可否添加下支持，谢谢。

首先通过npm安装`hexo-math`, 不知道为什么要连续执行两次才能执行成功.

``` bash
npm install hexo-math --save
npm install hexo-math --save
```

修改网站根目录的`_config.yml`, 添加如下内容: 

```
math:
  engine: 'mathjax' # or 'katex'
  mathjax:
    src: "//cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"
    config:
      # MathJax config
```
用法在: [hexo-math](https://github.com/hexojs/hexo-math)
推荐使用`{% math %}...{% endmath %}`这样的写法.
