### ISSUE TITLE
表格显示无格式问题

### ISSUE THREAD

**Issue by unionepro** [ahonn/hexo-theme-even#226]
用了这个主题，但是显示出的表格像没有添加任何格式一样。表格的代码如下：

``` Markdown
| Item      | Value    | Qty  |
| :-------: | --------:| :--: |
| Computer  | 1600 USD | 5    |
| Phone     | 12 USD   | 12   |
| Pipe      | 1 USD    | 234  |
```
但显示出来的却是如下图这样的，好像没有任何格式设置。试了Safari, Chrome, Firefox都是如此。
<img width="192" alt="2018-12-28 2 11 45" src="https://user-images.githubusercontent.com/20141852/50505034-4b91a680-0aac-11e9-84a8-801e9c5b24a8.png">

看了源代码，发现在样式文件`even/source/css/_partial/_post/_content.scss`中以下内容复制到.responsive-table定义之外可以解决显示问题。这个不知道是代码的问题，还是我哪里出错了？
``` SCSS
  table {
      width: 100%;
      max-width: 100%;
      border-spacing: 0;
      box-shadow: 2px 2px 3px rgba(0,0,0,.125);
 
      thead {
        background: $deputy-color;
      }
 
      th, td {
        padding: 5px 15px;
        border: 1px double $content-table-border-color;
      }
  }
```
