### ISSUE TITLE
mermaid 渲染时好时坏

### ISSUE THREAD

**Issue by lucmann** [ahonn/hexo-theme-even#299]
# 描述

不知道是网络原因，还是其它问题，mermaid diagram 有时渲染得出来，有时却出不来（同一个 diagram)

![image](https://github.com/user-attachments/assets/b05e310f-8995-44dc-ad0e-8fadfee81dac)

# [主题配置](https://github.com/lucmann/hexo-theme-even/blob/d5d1c314c3de0108558d7c820795ef6800abf715/_config.yml#L138)

```
mermaid:
  version: "11.2.1"
  enable: true
  theme: forest
  options:
    startOnload: true
```

# mermaid.swig

```
{%- if theme.mermaid.enable -%}
  <script src='https://unpkg.com/mermaid@{{ theme.mermaid.version }}/dist/mermaid.min.js'></script>
  <script>
    if (window.mermaid) {
      mermaid.initialize({{ JSON.stringify(theme.mermaid.options) }});    
    }
  </script>
{%- endif -%}
```
