### ISSUE TITLE
achieves 页文档数量

### ISSUE THREAD

**Issue by quentin-chen** [ahonn/hexo-theme-even#59]
在设置中 无论修改 `per_page` 为多少都只显示10篇文档，需要在achieves/index 里面做什么修改么？
```yaml
# Generator-archive
archive_generator:
  per_page: 15  # 归档页文章数, 参数为 0 时不分页
  yearly: false
  monthly: false
  daily: false
```
